name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Checkout Repo
        uses: actions/checkout@v2.7.0
      - name: Build JAR
        run: |
          javac -d bin src/cx/ksim/mather/*.java
          jar cf Mather.jar -C bin .
      - name: Release JAR
        uses: actions/upload-artifact@v2
        with:
          name: Mather
          path: Mather.jar
