name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Print & List Working Directory
        run: |
          pwd
          ls -l
      - name: Build JAR
        run: |
          javac -d bin src/cx/ksim/mather/*.java
          jar cf Mather.jar -C bin .
      - name: Release JAR
        uses: actions/upload-artifact@v2
        with:
          name: Mather
          path: Mather.jar
